# Generated by Django 5.1.1 on 2024-09-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_serviceprovider_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='on_hold_periods',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='ticket',
            name='time_in_progress',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
