# Generated by Django 5.1.1 on 2024-09-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_on_hold_periods_ticket_time_in_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='on_hold_periods',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
