# Generated by Django 5.1.1 on 2024-09-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_ticket_difficulty_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('normal', 'عادي'), ('medium', 'متوسط'), ('high', 'مرتفع')], max_length=20, null=True),
        ),
    ]
