# Generated by Django 5.1.1 on 2024-10-05 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_alter_ticket_difficulty_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='tickets.customuser', verbose_name='تم تعيينها إلى'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to='tickets.customuser', verbose_name='أنشأ بواسطة'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.group', verbose_name='المجموعة'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='الملاحظات'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='on_hold_periods',
            field=models.JSONField(blank=True, default=list, verbose_name='فترات التعليق'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time_in_progress',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التقدم'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time_resolved',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time_started',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البدء'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=255, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
    ]
